export const POLISH_CITIES: readonly string[] = [
  "Warszawa",
  "Kraków",
  "Łódź",
  "Wrocław",
  "Poznań",
  "Gdańsk",
  "Szczecin",
  "Bydgoszcz",
  "Lublin",
  "Białystok",
  "Katowice",
  "Gdynia",
  "Częstochowa",
  "Radom",
  "Sosnowiec",
  "Toruń",
  "Kielce",
  "Rzeszów",
  "Gliwice",
  "Zabrze",
  "Olsztyn",
  "Bielsko-Biała",
  "Bytom",
  "Zielona Góra",
  "Rybnik",
  "Ruda Śląska",
  "Tychy",
  "Opole",
  "Gorzów Wielkopolski",
  "Elbląg",
  "Płock",
  "Wałbrzych",
  "Włocławek",
  "Tarnów",
  "Chorzów",
  "Kalisz",
  "Koszalin",
  "Legnica",
  "Grudziądz",
  "Słupsk",
  "Jaworzno",
  "Jastrzębie-Zdrój",
  "Nowy Sącz",
  "Jelenia Góra",
  "Siedlce",
  "Mysłowice",
  "Piła",
  "Konin",
  "Piotrków Trybunalski",
  "Inowrocław",
  "Lubin",
  "Ostrowiec Świętokrzyski",
  "Suwałki",
  "Stargard",
  "Gniezno",
  "Ostrów Wielkopolski",
  "Siemianowice Śląskie",
  "Głogów",
  "Pabianice",
  "Zamość",
  "Chełm",
  "Tomaszów Mazowiecki",
  "Przemyśl",
  "Stalowa Wola",
  "Kędzierzyn-Koźle",
  "Tczew",
  "Będzin",
  "Zawiercie",
  "Biała Podlaska",
  "Racibórz",
  "Legionowo",
  "Piekary Śląskie",
  "Świdnica",
  "Skierniewice",
  "Starachowice",
  "Wejherowo",
  "Bełchatów",
  "Puławy",
  "Mielec",
  "Świnoujście",
  "Ostrołęka",
  "Żory",
  "Dąbrowa Górnicza",
  "Ełk",
  "Nysa",
  "Wodzisław Śląski",
  "Sopot",
  "Sanok",
  "Krosno",
  "Skarżysko-Kamienna",
  "Zgierz",
  "Otwock",
  "Kutno",
  "Malbork",
  "Mikołów",
  "Knurów",
  "Ciechanów",
  "Zakopane",
  "Giżycko",
  "Augustów",
  "Krynica-Zdrój",
];
